[package]
name = "typst-preprocess"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "prequery-preprocess"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.86"
async-trait = "0.1.80"
clap = { version = "4.5.7", features = ["derive", "env"] }
itertools = "0.13.0"
once_cell = "1.19.0"
reqwest = "0.12.5"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["full"] }
toml = "0.8.14"
typst-syntax = { git = "https://github.com/typst/typst/", version = "0.11.0" }
